Cesium
Tailormap/tailormap-viewer pull request #617
Opened 2024-04-24 13:31 UTC by steinkobben

2025-01-31 16:24 UTC, mprins requested changes
~~something is off in the deployment, seems to be an undefined problem~~ with new backed deployed, seems to be working: https://snapshot.tailormap.nl/pull-request/617/cesium/nl/app/3d_utrecht

2025-02-12 11:40 UTC, geertplaisier requested changes

2025-02-13 10:15 UTC, geertplaisier requested changes

2025-02-13 10:15 UTC, geertplaisier commented on projects/shared/src/lib/components/tree/tree.component.ts
> +  public singleLayerChecked = false;
Check if this can be removed if you use `useRadioInputs` instead

2025-02-14 13:30 UTC, mprins commented on projects/core/src/lib/components/toolbar/switch3D/switch3-d.component.ts
> +  private disallowingComponents = [
`disabledComponents` and `disabledTools` ?

2025-03-07 10:36 UTC, geertplaisier requested changes

2025-03-07 10:36 UTC, geertplaisier commented on projects/admin-core/src/lib/application/application-layer-settings/application-layer-settings.component.ts
> +    this.store$.select(selectGeoServiceLayersByGeoServiceId(serviceLayer?.service.id))
This is not how RxJS should be used. You should return an Observable and you can map the selector to a list of crs strings

2025-03-07 10:36 UTC, geertplaisier commented on projects/admin-core/src/lib/catalog/geo-service-layer-details/geo-service-layer-details.component.ts
> +        this.store$.select(selectGeoServiceLayersByGeoServiceId(serviceAndLayer?.service.id))
See earlier comment should return an RxJS Observable here

2025-03-07 10:36 UTC, geertplaisier commented on projects/core/src/lib/components/feature-info/feature-info/feature-info.component.ts
> +          this.store$.select(selectIn3DView).pipe(take(1)).subscribe(in3DView => {
Why not remove this tap, use the evt.cesiumFeatureInfo in `this.featureInfoService.fetchFeatures$` so we have all getting feature info (either from WMS, JDBC or cesiumFeatureInfo) in a single service.

2025-03-07 10:36 UTC, geertplaisier commented on projects/core/src/lib/components/feature-info/feature-info/feature-info.component.ts
> +    this.mapService.getCesiumLayerManager$().pipe(take(1)).subscribe(cesiumLayerManager => {
As metioned before, RxJS should not be used to execute synchronous code like this.

2025-03-07 10:36 UTC, geertplaisier commented on projects/core/src/lib/components/feature-info/feature-info/feature-info.component.ts
> +  private featureInfo3DToResponse(cesiumFeatureInfo: FeatureInfo3DModel): FeatureInfoResponseModel {
See comment above, could be moved to feature info service as well

2025-03-07 10:36 UTC, geertplaisier commented on projects/core/src/lib/components/toolbar/switch3D/switch3-d.component.ts
> +              this.store$.select(selectLayer(layerId))
Incorrect RxJS usage. Why would we need nested subscriptions here and also modifiying variables outside the subscription?

2025-03-07 10:36 UTC, geertplaisier commented on projects/core/src/lib/map/state/map.reducer.ts
> +  layersWithoutWebMercator: LayerModelHelper.filterLayersWithoutWebMercator(payload.appLayers, payload.services)
Don't think this should be in the state if I understand correctly. Think this should be in a selector since we are adding duplicate data to the state here. appLayers en services are already in the state so the filtering can be done when selecting the data using a selector.

2025-03-07 10:36 UTC, geertplaisier commented on projects/core/src/lib/map/state/map.state.ts
> +  layersWithoutWebMercator: string[];
see earlier comment, should not be in the state

2025-03-07 10:36 UTC, geertplaisier commented on projects/shared/src/lib/components/split-button/split-button-option.model.ts
> +  webMercatorAvailable?: boolean;
Should not be added here. This is a shared component, could be used anywhere (also not map related at all) so a map specific (webMercatorAvailable) property does not belong here. Much better to add for example a 'className' property which you can pass from the 'parent' component

2025-03-07 10:36 UTC, geertplaisier commented on projects/map/src/lib/openlayers-map/tools/open-layers-map-click-tool.ts
> +    this.in3D$.pipe(
Would rather move this to the `CesiumEventManager` code. Check there if you are in 3d or not, return `undefined` or `null` when not in 3d and the actual event if you are. Same for `OpenLayersEventManager`, there here it can be a simple check and then there is also no need to pass the 3d$ observable as constructor param

2025-03-13 12:24 UTC, geertplaisier requested changes

2025-03-13 12:24 UTC, geertplaisier commented on projects/map/src/lib/openlayers-map/cesium-map/cesium-layer-manager.ts
> +export class CesiumLayerManager {
Rename to CesiumManager to better reflect what the class does

2025-03-13 12:24 UTC, geertplaisier commented on projects/core/src/lib/components/feature-info/feature-info.service.ts
> +    if (cesiumFeatureInfo) {
Can be removed if changes to Cesium(Event)Manager are applied

2025-03-13 12:24 UTC, geertplaisier commented on projects/core/src/lib/map/services/application-map.service.ts
> +            layerManager.addLayers(layers.filter(isValidLayer));
Try to prevent subscriptions inside subscriptions

2025-03-13 12:24 UTC, geertplaisier commented on projects/core/src/lib/map/state/map.selectors.ts
> +export const selectLayersWithoutWebMercatorIds = createSelector(
Small improvement suggestion

```
const selectLayersWithoutWebMercator = createSelector(
  selectLayers,
  selectServices,
  (layers, services) => LayerModelHelper.filterLayersWithoutWebMercator(layers, services),
);

export const selectLayersWithoutWebMercatorIds = createSelector(
  selectLayersWithoutWebMercator,
  layers => layers.map(layer => layer.id),
);

export const selectLayersWithoutWebMercatorTitles = createSelector(
  selectLayersWithoutWebMercator,
  layers => layers.map(layer => layer.title),
);
```

2025-03-21 13:06 UTC, geertplaisier approved these changes

2025-03-21 13:12 UTC, merged