HTM-981 Change background-layer-toggle to show ellipsis when title is too long
Tailormap/tailormap-viewer pull request #715
Opened 2024-10-01 12:59 UTC by steinkobben

* Set maximum characters to 30 for layers titles in layer forms. (30 is the amount of characters that fits in the new drop-down menu width)
* Set maximum width for background-layer toggle button (cycle button) to not overlap with other components.
* Show ellipsis in cycle button when the text does not fit in the cycle button.
* Show ellipsis in background-layer-toggle drop-down menu if text does not fit.
* Increased maximum width of background-layer-toggle drop-down menu to 360px (maximum width that still looks good when the screen is at the lowest width without components overlapping (570px))

2024-10-02 09:08 UTC, mprins requested changes
I don't see a matching PR to limit the title length in the API, which makes this a cosmetic change only.
Also I don't see an ellipsis appear when I change the title of a layer to `een hele lange titel voor deze laag, meer dan 30 tekens` eg on the OBK TMS layer, instead the dropdown adds line breaks and the hover over the items in the expanded dropdown is "funny" in that there appear to be more items thin that one layer

2024-10-04 11:43 UTC, geertplaisier submitted a review, later dismissed

2024-10-04 11:43 UTC, geertplaisier commented on projects/admin-core/src/lib/application/application-layer-settings/application-layer-settings.component.html
> +    <input matInput maxlength="30" formControlName="title" />
As discussed we dont impose a max lenght for now

2024-10-07 09:37 UTC, mprins approved these changes
lgtm

2024-10-07 09:38 UTC, merged