HTM-1248: Add crosshair cursor for coordinate-link-window and streetview
Tailormap/tailormap-viewer pull request #742
Opened 2024-11-06 16:48 UTC by geertplaisier

2024-11-07 10:20 UTC, mprins requested changes
What about "coordinate picker", I think that should get the crosshair as well

2024-11-07 10:20 UTC, mprins commented on projects/map/src/lib/map/crosshair-cursor.png
on a high resolution screen this is tiny; much smaller that the regular cursor

2024-11-07 10:20 UTC, mprins commented on projects/map/src/lib/map/map.component.css
> +  cursor: url("crosshair-cursor.png"), crosshair;
I would prefer having the OS/user provided cursor

2024-11-11 10:52 UTC, matthijsln commented
Native cursor looks good on Linux but if on MacOS it's not visible enough there are options to use a bigger icon with scaling: https://stackoverflow.com/questions/51902842/is-it-possible-to-scale-a-custom-cursor-image-using-css

2024-11-11 10:55 UTC, matthijsln approved these changes

2024-11-11 10:58 UTC, mprins approved these changes

2024-11-11 10:58 UTC, merged