HTM-1324 (revised): Added translation for 'Description*'
Tailormap/tailormap-viewer pull request #763
Opened 2024-11-26 10:39 UTC by steinkobben

2024-11-26 12:25 UTC, geertplaisier commented
This is not how is should be done. The form field should be marked required (`Validators.required`) to add the star automatically. We should not add the star in text in the template and translation.

2024-11-26 14:48 UTC, mprins requested changes

2024-11-26 15:57 UTC, steinkobben commented on projects/admin-core/src/lib/search-index/search-index-scheduling/search-index-scheduling.component.ts
> +    description: new FormControl('', {
Omitting the description in the request to the back-end gives an internal server error. I will fix this in the back-end and set this to not required.

2024-11-29 12:35 UTC, mprins approved these changes

2024-11-29 12:37 UTC, merged

2024-11-29 12:37 UTC, geertplaisier approved these changes